refactor(auth): Use `self.authenticate_header()` in `authenticate()` method to get auth header prefix
jazzband/django-rest-knox pull request #329
Opened 2024-01-26 07:18 UTC by luqmansen

As titled, seems like the `TokenAuthentication` class already defined a method to retrieve the header, yet not utilized within the class itself.

This change allows the auth header to be overridden from the subclass without having to override the `authenticate()` method. 

[Similar technique](https://github.com/encode/django-rest-framework/blob/2797c0f216288bd7ca82e9e32e5f7d699bac74df/rest_framework/authentication.py#L180) has been done in `rest_framework` Token Authentication (though, through class attribute)

2024-01-26 10:36 UTC, johnraz requested changes
if you can get rid of the 2 first commits I will approve !

Thanks for the contribution 👌🏻

2024-01-27 08:31 UTC, giovannicimolin commented
@luqmansen Thank you for your contribution! :grin:

@johnraz I think we can use GitHub's `Squash and Merge` feature to merge these changes in. :wink:

2024-01-27 08:45 UTC, johnraz commented
@giovannicimolin indeed that would give the same result, we just need to make sure the commit message is proper 😊

2024-01-28 07:31 UTC, luqmansen commented
Hi @johnraz, I have dropped the unneeded commit, thank you for reviewing :adore:

2024-01-28 07:49 UTC, giovannicimolin approved these changes
:+1: 

Looks good! LGTM.

2024-01-28 17:35 UTC, merged