Remove EOL versions
jazzband/django-rest-knox pull request #345
Opened 2024-05-06 14:54 UTC by calumy

This PR removes the following end-of-life versions of [Python](https://devguide.python.org/versions/) and [Django](https://jefftriplett.com/django-release-cycle/): 
- Python 3.6 - EOL: 23rd December 2021
- Python 3.7 - EOL: 27th June 2023
- Django 3.2 - EOL:  April 2024 

In addition to removing the EOL versions, the [Django upgrade pre-commit hook](https://github.com/adamchainz/django-upgrade) has also been added, and fixes are included in this PR. These changes relate to:
- The use of `USE_L10N`, which was deprecated in Django 4.0: https://github.com/adamchainz/django-upgrade?tab=readme-ov-file#use_l10n
- The use of `re_path`, which has been rewritten using the `path()` syntax added in Django 2.0: https://github.com/adamchainz/django-upgrade?tab=readme-ov-file#urls

2024-05-06 20:59 UTC, johnraz requested changes
I was thinking we could merge this after the next release, like that we can issue a warning that this will be the last release to support all those older versions.

2024-05-07 09:31 UTC, calumy commented
Drafting until #342 is merged and a new version released.

2024-07-19 19:09 UTC, johnraz approved these changes
LGTM

2024-07-22 17:37 UTC, merged

2024-07-22 17:38 UTC, giovannicimolin commented
@calumy Thanks for your contribution! :)

I'll update the changelogs and documentation of the before the next release and be sure to add a note.